- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container
      shell: >
        docker run -d -p 3000:3000 helenhaveloh/k8s-application
      args:
        executable: /bin/bash
